name: docs

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2

      - name: Use node v16
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: build examples
        run: |
          cd examples
          npm install yarn
          yarn 
          yarn build
          cd -
          rm -rf ./deploy
          mkdir -p deploy/examples
          mkdir -p deploy/docs
          cp -rf index.html ./deploy
          cp -rf ./docs/* ./deploy/docs
          cp -rf ./examples/dist/* ./deploy/examples

      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          force_orphan: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          cname: docs.logic-flow.cn
